# 主参数文件 - 导入其他配置文件
/**:
  ros__parameters:
    use_sim_time: True
    
# 导入各个子配置文件
amcl:
  ros__parameters:
    &amcl_params
    __import: "config/nav2_params/amcl_params.yaml"

bt_navigator:
  ros__parameters:
    &bt_navigator_params
    __import: "config/nav2_params/bt_navigator_params.yaml"

controller_server:
  ros__parameters:
    &controller_params
    __import: "config/nav2_params/controller_params.yaml"

planner_server:
  ros__parameters:
    &planner_params
    __import: "config/nav2_params/planner_params.yaml"

global_costmap:
  ros__parameters:
    &global_costmap_params
    __import: "config/nav2_params/global_costmap.yaml"

local_costmap:
  ros__parameters:
    &local_costmap_params
    __import: "config/nav2_params/local_costmap.yaml"

behavior_server:
  ros__parameters:
    __import: "config/nav2_params/behavior_params.yaml"
